name: aiapparel
description: A wardorbe sorter.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

#Packages
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  image_picker: ^1.0.7
  firebase_storage: ^11.6.7
  file_picker: ^6.1.1
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_native_splash: ^2.3.10
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.1.0
  url_launcher: ^6.2.5
  smooth_page_indicator: ^1.1.0
  iconsax: ^0.0.8
  lottie: ^3.1.0
  connectivity_plus: ^5.0.2
  cloud_firestore: ^4.15.8
  google_sign_in: ^6.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  google_mlkit_image_labeling: ^0.12.0
  carousel_slider: ^4.2.1
  readmore: ^3.0.0
  palette_generator: ^0.3.3+3
  google_mlkit_text_recognition: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
#assets
  assets:
    - assets/logos/
    - assets/icons/
    - assets/icons/categories/
    - assets/icons/brands/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/items/
    - assets/images/user/
