// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChlrgP6KeFmeQ-9Edo0_JezoSxkOs2ZS4',
    appId: '1:545736445073:web:f4c54597396eb455390330',
    messagingSenderId: '545736445073',
    projectId: 'aiparrel-84c69',
    authDomain: 'aiparrel-84c69.firebaseapp.com',
    storageBucket: 'aiparrel-84c69.appspot.com',
    measurementId: 'G-XTXHXNE4XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwu9MCJRAAKU4SQk7xPb0Jn-wOQHmX8VM',
    appId: '1:545736445073:android:585675f67a17896e390330',
    messagingSenderId: '545736445073',
    projectId: 'aiparrel-84c69',
    storageBucket: 'aiparrel-84c69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWMKKXIYvO82tpGftx6BGppuYtUnEsmJ0',
    appId: '1:545736445073:ios:17f9cc80bf5fb14f390330',
    messagingSenderId: '545736445073',
    projectId: 'aiparrel-84c69',
    storageBucket: 'aiparrel-84c69.appspot.com',
    androidClientId: '545736445073-23bt1fkc9dj81jsm4k6jkgf6be23p6rs.apps.googleusercontent.com',
    iosClientId: '545736445073-94stcreb2qvst7soidckp0auv3no4hgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiapparel',
  );
}
